### ISSUE TITLE
ginkgo reports "undefined: Specify" in go 1.8

### ISSUE THREAD

**Issue by sbchand** [onsi/ginkgo#334]
The following command was working with go 1.7.4; however, it reports "undefined: Specify" with go 1.8 on line numbers wherever the keyword "Specify" is mentioned in the test file.  While replacing "Specify" with "It" works, wish to know if there are any changes/issues around this; thanks in advance.

ginkgo -r --failOnPending --cover --trace --noColor --progress --slowSpecThreshold 1 --randomizeAllSpecs --randomizeSuites .

**Comment by sbchand** [comment]
I found the root cause…in addition to upgrading go to 1.8, was using release/tag version of ginkgo 1.2.0 instead of master branch.

“Specify” was introduced in January 2016
https://github.com/onsi/ginkgo/pull/216 

However the latest version released is 1.2.0 (which we are using) on June 2015
https://github.com/onsi/ginkgo/releases

Therefore “Specify” may not be available in this version.
