### ISSUE TITLE
Multiple definition errors despite ldflags set with go 1.10

### ISSUE THREAD

**Issue by ameowlia** [onsi/ginkgo#435]
## Issue

When we run this code (note, `--allow-multiple-definition` flag is set) on go 1.10: 
```
ginkgo -r -focus="CNI Integration Suite" -p --race -randomizeAllSpecs -randomizeSuites \
  -ldflags "-extldflags=-Wl,--allow-multiple-definition" \
  ${@}
```

we see this multiple definition error from cgo:
```
  Expected error:
      <*errors.errorString | 0xc420206020>: {
          s: "Failed to build code.cloudfoundry.org/silk/cmd/silk-cni:\n\nError:\nexit status 2\n\nOutput:\n# code.cloudfoundry.org/silk/cmd/silk-cni\n/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1\n/tmp/go-link-775132932/000023.o: In function `_cgo_f36fc5609ae4_C2func_load_simple_bpf':\n/tmp/go-build/cgo-gcc-prolog:32: multiple definition of `_cgo_f36fc5609ae4_C2func_load_simple_bpf'\n/tmp/go-link-775132932/000021.o:/tmp/go-build/cgo-gcc-prolog:32: first defined here\n/tmp/go-link-775132932/000023.o: In function `_cgo_f36fc5609ae4_Cfunc_load_simple_bpf':\n/tmp/go-build/cgo-gcc-prolog:55: multiple definition of `_cgo_f36fc5609ae4_Cfunc_load_simple_bpf'\n/tmp/go-link-775132932/000021.o:/tmp/go-build/cgo-gcc-prolog:55: first defined here\ncollect2: error: ld returned 1 exit status\n\n",
      }
      Failed to build code.cloudfoundry.org/silk/cmd/silk-cni:

      Error:
      exit status 2

      Output:
      # code.cloudfoundry.org/silk/cmd/silk-cni
      /usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
      /tmp/go-link-775132932/000023.o: In function `_cgo_f36fc5609ae4_C2func_load_simple_bpf':
      /tmp/go-build/cgo-gcc-prolog:32: multiple definition of `_cgo_f36fc5609ae4_C2func_load_simple_bpf'
      /tmp/go-link-775132932/000021.o:/tmp/go-build/cgo-gcc-prolog:32: first defined here
      /tmp/go-link-775132932/000023.o: In function `_cgo_f36fc5609ae4_Cfunc_load_simple_bpf':
      /tmp/go-build/cgo-gcc-prolog:55: multiple definition of `_cgo_f36fc5609ae4_Cfunc_load_simple_bpf'
      /tmp/go-link-775132932/000021.o:/tmp/go-build/cgo-gcc-prolog:55: first defined here
      collect2: error: ld returned 1 exit status

```

## Context

We are seeing this error because two different packages have vendored the exact same code. This issue is detailed here: https://github.com/golang/go/issues/23555

We have mitigated this in the past on 1.9 by using the `allow-multiple-definitions` flag.

When we `go build` the code ourselves on go 1.10 with the `allow-multiple-defintions` flag, it does not error, but without the flag it does.

```
root@da4476e4-443d-47f0-5dd7-10c74c847fe5:/tmp/build/3be5e44b/go/src/code.cloudfoundry.org/silk/cmd/silk-cni# go build -ldflags "-extldflags=-Wl,--allow-multiple-definition"
root@da4476e4-443d-47f0-5dd7-10c74c847fe5:/tmp/build/3be5e44b/go/src/code.cloudfoundry.org/silk/cmd/silk-cni# go build
# code.cloudfoundry.org/silk/cmd/silk-cni
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/tmp/go-link-759944476/000020.o: In function `_cgo_f36fc5609ae4_C2func_load_simple_bpf':
/tmp/go-build/cgo-gcc-prolog:32: multiple definition of `_cgo_f36fc5609ae4_C2func_load_simple_bpf'
/tmp/go-link-759944476/000006.o:/tmp/go-build/cgo-gcc-prolog:32: first defined here
/tmp/go-link-759944476/000020.o: In function `_cgo_f36fc5609ae4_Cfunc_load_simple_bpf':
/tmp/go-build/cgo-gcc-prolog:55: multiple definition of `_cgo_f36fc5609ae4_Cfunc_load_simple_bpf'
/tmp/go-link-759944476/000006.o:/tmp/go-build/cgo-gcc-prolog:55: first defined here
collect2: error: ld returned 1 exit status
```

Because we can build it ourselves with 1.10, but ginkgo doesn't work with the same flag set, we think this issue is with ginkgo passing flags. 

## Steps to Reproduce

1. install go 1.10 on a linux machine
2. clone our repo and run [this file](https://github.com/cloudfoundry/silk/blob/master/scripts/test.sh)
3. see it fail :( 

## Expected result

it compiles and all the tests pass!

## Current result

it fails to compile

## Possible Fix

go 1.10 has changed things around flags? Maybe the way ginkgo is shell-ing out and setting flags is no longer correct?

**Comment by ameowlia** [comment]
Turns out we we were calling: 

```
/usr/local/go/bin/go build '-ldflags="-extldflags=-Wl,--allow-multiple-definition"' -race -o /our/package/here
```

which works with 1.9, but doesn't work in 1.10 because of the single quotes.
